# Generated by Django 5.0.4 on 2024-04-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_solid',
            new_name='is_sold',
        ),
    ]
